[display]
collapse_preview = false
scroll_offset    = 8
show_icons       = true
column_ratio     = [ 1, 4, 3 ]

	[display.sort]
	method            = "mtime"
	directories_first = false

[preview]
max_preview_size            = 999999999  # I prefer to limit it in the scripts for various file types
preview_script              = "~/.config/joshuto/scripts/preview.sh"
preview_shown_hook_script   = "~/.config/joshuto/scripts/show_image.sh"
preview_removed_hook_script = "~/.config/joshuto/scripts/remove_image.sh"

